version: "3.8"

services:
  postgres:
    env_file: ${DOT_ENV_FILE:-.env-none}
    restart: always
    image: postgres:${PG_VERSION:-12.5}-alpine
    container_name: ${PG_CONTAINER:-pg-docker}
    ports:
      - ${PG_PORT:-5432}:5432
    networks:
      - ${PG_NETWORK:-postgres}
    environment:
      POSTGRES_USER: ${PG_USER:-postgres}
      POSTGRES_PASSWORD: ${PG_PASS:-docker}
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - pgvol:/var/lib/postgresql/data:delegated
  pgAdmin:
    env_file: ${DOT_ENV_FILE:-.env-none}
    restart: always
    image: dpage/pgadmin4
    container_name: ${PGA_CONTAINER:-pg-admin}
    ports:
      - ${PGA_PORT:-8010}:80
    networks:
      - ${PG_NETWORK:-postgres}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_USER:-mail@mail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASS:-pass}
    volumes:
      - pgavol:/var/lib/pgadmin:delegated
volumes:
  pgvol:
  pgavol:

networks:
  postgres:
    name: ${PG_NETWORK:-postgres}
