version: "3.8"

services:
  postgres:
    restart: always
    image: postgres:${PG_VERSION}
    container_name: ${PG_CONTAINER}
    ports:
      - ${PG_PORT}:5432
    networks:
      - ${PG_NETWORK}
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASS}
    command: ["postgres", "-c", "log_statement=all", "-c", "log_destination=stderr"]
    volumes:
      - pgvol:/var/lib/postgresql/data:delegated
  pgAdmin:
    restart: always
    image: dpage/pgadmin4
    container_name: ${PGA_CONTAINER}
    ports:
      - ${PGA_PORT}:80
    networks:
      - ${PG_NETWORK}
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGA_USER}
      PGADMIN_DEFAULT_PASSWORD: ${PGA_PASS}
    volumes:
      - pgavol:/var/lib/pgadmin:delegated
volumes:
  pgvol:
  pgavol:

networks:
  postgres:
    name: ${PG_NETWORK}
